--Puzzle.1
SELECT S1.ID, 
	   S1.Score,
	   (SELECT COUNT(DISTINCT S2.Score) FROM Scores S2 WHERE S2.Score>S1.Score) + 1 AS Rank 
FROM Scores S1
ORDER BY 2 DESC;

--Puzzle.2
WITH CTE AS (
SELECT 'MM' AS EDU, 0.5 AS POINT
UNION ALL
SELECT 'CI' AS EDU, 0.5 AS POINT
UNION ALL
SELECT 'CO' AS EDU, 0.5 AS POINT
UNION ALL
SELECT 'CD' AS EDU, 1 AS POINT
UNION ALL
SELECT 'CL' AS EDU, 1 AS POINT
UNION ALL
SELECT 'CM' AS EDU, 1 AS POINT )

SELECT C.CLUB_ID, ISNULL(SUM(CTE.POINT),0) AS TOTAL_POINT FROM CLUB C OUTER APPLY STRING_SPLIT(C.EDU, ':') AS S LEFT JOIN CTE ON S.VALUE = CTE.EDU
GROUP BY C.CLUB_ID;

--Puzzle.3
WITH CTE AS (
SELECT *, ROW_NUMBER() OVER (PARTITION BY [GROUP] ORDER BY SEQUENCE) RN FROM EMP),
CTE1 AS (
SELECT *, SEQUENCE- RN AS GRP FROM CTE)
SELECT [GROUP], 
	   MIN(SEQUENCE) AS Min_Seq, 
	   MAX(SEQUENCE) AS Max_Seq 
FROM CTE1
GROUP BY [GROUP], GRP
ORDER BY 1;

--Puzzle.4
WITH CTE AS (
SELECT CHAR(65 + N) AS Row
FROM (SELECT 0 AS N 
UNION ALL 
SELECT 1 
UNION ALL 
SELECT 2 
UNION ALL 
SELECT 3 
UNION ALL
SELECT 4 
UNION ALL 
SELECT 5 
UNION ALL 
SELECT 6 
UNION ALL 
SELECT 7 
UNION ALL
SELECT 8 
UNION ALL 
SELECT 9 
UNION ALL 
SELECT 10) AS NUMS
WHERE n <= 10
),
CTE1 AS (
SELECT C.Row, 
	   C.Row + CAST(S.N AS VARCHAR) AS Seat
FROM CTE C
CROSS JOIN (SELECT N FROM (VALUES (1),(2),(3),(4),(5),(6),(7),(8),(9),(10)) AS S(N)) S
)

SELECT Row, 
	   STRING_AGG(Seat, ',') AS Seat_Arrangement
FROM CTE1
GROUP BY Row;

