--1.Fix with zero.
--0 bilan tog'irlangan

SELECT *, 
       IIF(MONTH(DT) <= 9, '0' + CAST(MONTH(Dt) AS VARCHAR(MAX)), CAST(MONTH(DT) AS VARCHAR(MAX))) AS MonthPrefixedWithZero
FROM Dates;

--2.SUM of max vals and distinct ids.
--Engkatta qiymatlar yig'indisi va takrorlanmagan id lar.

SELECT COUNT(ID) AS Distinct_Ids,
       rID,
       SUM(MAX_VALS) AS TotalOfMaxVals
FROM
  (SELECT ID,
          MAX(Vals) AS MAX_VALS,

     (SELECT DISTINCT rID
      FROM MyTabel) AS rID
   FROM MyTabel
   GROUP BY Id) AS A
GROUP BY rID;

--3.Minimum 6 character length and maximum 10 character length.
--Uzunligi kamida 6 va ko'pi bilan 10 bo'lganlar.

SELECT ID,
       Vals
FROM TestFixLengths
WHERE LEN(Vals) BETWEEN 6 AND 10;

--4.Max val for each id.
--Har bir id uchun eng katta qiymat.

SELECT ID,
       Item,
       Vals
FROM
  (SELECT ID,
          Item,
          Vals,
          ROW_NUMBER() OVER (PARTITION BY ID
                             ORDER BY VALS DESC) AS RN
   FROM TestMaximum) AS A
WHERE RN=1;

--5.Sum of maximum vals by id and detailed number.
--Son va id bo'yicha eng katta qiymatlarning yig'indisi.

SELECT Id,
       SUM(MAX_VAL)
FROM
  (SELECT DetailedNumber,
          ID,
          MAX(Vals) AS MAX_VAL
   FROM SumOfMax
   GROUP BY DetailedNumber,
            Id) AS A
GROUP BY Id;

--6.Difference between a and b.
--A va b orasidagi farq.

SELECT Id,
       a,
       b,
       IIF(A-B = 0, '', CAST(A-B AS VARCHAR(MAX))) AS OUTPUT
FROM TheZeroPuzzle;

--7.Total revenue generated from all sales.
--Barcha mahsulotlardan olingan umumiy daromad.

SELECT SUM(QuantitySold * UnitPrice) AS TotalRevenue
FROM Sales;

--8.Average price of products.
--Mahsulotlarning o'rtacha narxi.

SELECT AVG(UnitPrice) AS AveragePrice
FROM Sales;

--9.Recorded sales transactions.
--Amalga oshirilgan sotuvlar.

SELECT COUNT(*) RecordedSalesTransactions
FROM Sales;

--10.Highest number of units sold in a single transaction.
--1 ta sotuvda eng ko'p buyurtma qilingan narsa.

SELECT MAX(QuantitySold) AS HighestUnitSold
FROM Sales;

--11.Number of sold products in each category.
--Har bir kategoriya bo'yicha soligan mahsulotlar soni.

SELECT Category,
       SUM(QuantitySold) AS TotalSoldProducts
FROM Sales
GROUP BY Category;

--12.Total revenue for each region.
--Har bir hudud bo'yicha umumiy daromad.

SELECT Region,
       SUM(QuantitySold * UnitPrice) AS TotalRevenue
FROM Sales
GROUP BY Region;

--13.Product that generated the hhighest total revenue.
--Eng katta daromad keltirgan mahsulot.

SELECT TOP 1 Product,
           SUM(QuantitySold * UnitPrice) AS TotalRevenue
FROM Sales
GROUP BY Product
ORDER BY 2 DESC;

--14.Running total revenue ordered by sale date.
--Ketma ket umumiy daromad sotuv sanasi bo'yicha.

SELECT SaleDate,
       SUM(QuantitySold * UnitPrice) OVER (
                                           ORDER BY SaleDate) AS TotalRevenue
FROM Sales;

--15.Total sales revenue that each category contributes.
--Har bir kategoriya umumiy daromadgan qo'shgan hissasi.

SELECT Category,
       SUM(QuantitySold * UnitPrice) AS TotalRevenue
FROM Sales
GROUP BY Category;

--17.Sales with corresponding customer names.
--Mijoz ismi bilan sotuvlar.

SELECT S.SaleID,
       C.CustomerName,
       S.Product,
       S.Category,
       S.QuantitySold,
       S.UnitPrice,
       S.SaleDate,
       S.Region
FROM Sales AS S
JOIN Customers AS C ON S.CustomerID = C.CustomerID;

--18.Customer who haven't any sale.
--Sotuv qilmagan mijoz.

SELECT *
FROM Customers
WHERE CustomerID NOT IN
    (SELECT CustomerID
     FROM Sales);

--19.Total revenue generated by each customer.
--Har bir mijoz uchun umumiy daromad.

SELECT C.CustomerName,
       SUM(S.QuantitySold * S.UnitPrice) AS TotalRevenue
FROM Sales AS S
JOIN Customers AS C ON S.CustomerID = C.CustomerID
GROUP BY C.CustomerName;

--20.Customer who has contributed the most revenue
--Eng ko'p daromad qo'shgan mijoz.

SELECT TOP 1 C.CustomerName,
           SUM(S.QuantitySold * S.UnitPrice) AS TotalRevenue
FROM Sales AS S
JOIN Customers AS C ON S.CustomerID = C.CustomerID
GROUP BY C.CustomerName
ORDER BY 2 DESC;

--21.Total sales per customer.
--Mijozlar bo'yicha jami sotuvlar.

SELECT C.CustomerName,
       COUNT(*) AS TotalSales
FROM Sales AS S
JOIN Customers AS C ON S.CustomerID = C.CustomerID
GROUP BY C.CustomerName;

--22.Products which have been sold at least once.
--Kamida 1 marta sotilgan mahsulotlar.

SELECT *
FROM Products
WHERE ProductName IN
    (SELECT Product
     FROM Sales);

--23.Most expensive product in Products table.
--Mahsulotlar jadvalidagi eng qimmat mahsulot.

SELECT TOP 1 ProductName,
           SellingPrice AS Price
FROM Products
ORDER BY 2 DESC;

--24.Products that have selling price is higher than average price in their category.
--O'z toifasidagi o'rtacha narxdan qimmat sotiladigan mahsulotlar.

SELECT P.ProductName,
       P.SellingPrice
FROM Products AS P
JOIN
  (SELECT Category,
          AVG(SellingPrice) AS AVG_PRICE
   FROM Products
   GROUP BY Category) AS A ON P.Category = A.Category
AND P.SellingPrice > A.AVG_PRICE;
